# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: |
      cd my-azure-app-insights
      echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      npm install
    command: |
      cd my-azure-app-insights
      echo 'start script'
      npm start

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
